server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 关闭缓存，上线才开启
  thymeleaf:
    cache: false


swagger2:
  enable: true

web:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    static-path-pattern: /swagger-ui.html

# 指定实体类
mybatis:
  type-aliases-package: com.gdufs.finalexam.entity
  # 指定mapper文件位置
  mapper-locations: classpath:mapper/*.xml

security:
  FilterChainProxy:
    - pattern: /v2/api-docs
      access: permitAll
    - pattern: /swagger-ui.html
      access: permitAll
    - pattern: /swagger-resources/**
      access: permitAll
    - pattern: /webjars/**
      access: permitAll